language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - LARAVEL='6.0.*' TESTBENCH='4.0.*'
    - LARAVEL='7.0.*' TESTBENCH='5.0.*'

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true

before_script: composer config discard-changes true

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install: travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit

